# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ni.measurements.metadata.v1 import metadata_store_service_pb2 as ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ni/measurements/metadata/v1/metadata_store_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetadataStoreServiceStub(object):
    """This service is responsible for storing and retrieving metadata associated with test step measurements.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUutInstance = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/GetUutInstance',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutInstanceRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutInstanceResponse.FromString,
                _registered_method=True)
        self.QueryUutInstances = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/QueryUutInstances',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutInstancesRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutInstancesResponse.FromString,
                _registered_method=True)
        self.CreateUutInstance = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/CreateUutInstance',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutInstanceRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutInstanceResponse.FromString,
                _registered_method=True)
        self.GetUut = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/GetUut',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutResponse.FromString,
                _registered_method=True)
        self.QueryUuts = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/QueryUuts',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutsRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutsResponse.FromString,
                _registered_method=True)
        self.CreateUut = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/CreateUut',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutResponse.FromString,
                _registered_method=True)
        self.GetOperator = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/GetOperator',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetOperatorRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetOperatorResponse.FromString,
                _registered_method=True)
        self.QueryOperators = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/QueryOperators',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryOperatorsRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryOperatorsResponse.FromString,
                _registered_method=True)
        self.CreateOperator = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/CreateOperator',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateOperatorRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateOperatorResponse.FromString,
                _registered_method=True)
        self.GetTestDescription = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/GetTestDescription',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestDescriptionRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestDescriptionResponse.FromString,
                _registered_method=True)
        self.QueryTestDescriptions = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/QueryTestDescriptions',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestDescriptionsRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestDescriptionsResponse.FromString,
                _registered_method=True)
        self.CreateTestDescription = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/CreateTestDescription',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestDescriptionRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestDescriptionResponse.FromString,
                _registered_method=True)
        self.GetTest = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/GetTest',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestResponse.FromString,
                _registered_method=True)
        self.QueryTests = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/QueryTests',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestsRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestsResponse.FromString,
                _registered_method=True)
        self.CreateTest = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/CreateTest',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestResponse.FromString,
                _registered_method=True)
        self.GetTestStation = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/GetTestStation',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestStationRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestStationResponse.FromString,
                _registered_method=True)
        self.QueryTestStations = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/QueryTestStations',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestStationsRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestStationsResponse.FromString,
                _registered_method=True)
        self.CreateTestStation = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/CreateTestStation',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestStationRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestStationResponse.FromString,
                _registered_method=True)
        self.GetHardwareItem = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/GetHardwareItem',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetHardwareItemRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetHardwareItemResponse.FromString,
                _registered_method=True)
        self.QueryHardwareItems = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/QueryHardwareItems',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryHardwareItemsRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryHardwareItemsResponse.FromString,
                _registered_method=True)
        self.CreateHardwareItem = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/CreateHardwareItem',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateHardwareItemRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateHardwareItemResponse.FromString,
                _registered_method=True)
        self.GetSoftwareItem = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/GetSoftwareItem',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetSoftwareItemRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetSoftwareItemResponse.FromString,
                _registered_method=True)
        self.QuerySoftwareItems = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/QuerySoftwareItems',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QuerySoftwareItemsRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QuerySoftwareItemsResponse.FromString,
                _registered_method=True)
        self.CreateSoftwareItem = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/CreateSoftwareItem',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateSoftwareItemRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateSoftwareItemResponse.FromString,
                _registered_method=True)
        self.GetTestAdapter = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/GetTestAdapter',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestAdapterRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestAdapterResponse.FromString,
                _registered_method=True)
        self.QueryTestAdapters = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/QueryTestAdapters',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestAdaptersRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestAdaptersResponse.FromString,
                _registered_method=True)
        self.CreateTestAdapter = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/CreateTestAdapter',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestAdapterRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestAdapterResponse.FromString,
                _registered_method=True)
        self.RegisterSchema = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/RegisterSchema',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.RegisterSchemaRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.RegisterSchemaResponse.FromString,
                _registered_method=True)
        self.ListSchemas = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/ListSchemas',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.ListSchemasRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.ListSchemasResponse.FromString,
                _registered_method=True)
        self.GetAlias = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/GetAlias',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetAliasRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetAliasResponse.FromString,
                _registered_method=True)
        self.QueryAliases = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/QueryAliases',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryAliasesRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryAliasesResponse.FromString,
                _registered_method=True)
        self.CreateAlias = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/CreateAlias',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateAliasRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateAliasResponse.FromString,
                _registered_method=True)
        self.DeleteAlias = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/DeleteAlias',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.DeleteAliasRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.DeleteAliasResponse.FromString,
                _registered_method=True)
        self.CreateFromJsonDocument = channel.unary_unary(
                '/ni.measurements.metadata.v1.MetadataStoreService/CreateFromJsonDocument',
                request_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateFromJsonDocumentRequest.SerializeToString,
                response_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateFromJsonDocumentResponse.FromString,
                _registered_method=True)


class MetadataStoreServiceServicer(object):
    """This service is responsible for storing and retrieving metadata associated with test step measurements.
    """

    def GetUutInstance(self, request, context):
        """Gets the UUT instance associated with the identifier given in the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryUutInstances(self, request, context):
        """Perform an OData query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUutInstance(self, request, context):
        """Creates a new UUT instance in the metadata store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUut(self, request, context):
        """Gets the UUT associated with the identifier given in the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryUuts(self, request, context):
        """Perform an OData query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUut(self, request, context):
        """Creates a new UUT in the metadata store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperator(self, request, context):
        """Gets the operator associated with the identifier given in the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryOperators(self, request, context):
        """Perform an OData query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOperator(self, request, context):
        """Creates a new operator in the metadata store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestDescription(self, request, context):
        """Gets the test description associated with the identifier given in the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTestDescriptions(self, request, context):
        """Perform an OData query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTestDescription(self, request, context):
        """Creates a new test description in the metadata store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTest(self, request, context):
        """Gets the test associated with the identifier given in the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTests(self, request, context):
        """Perform an OData query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTest(self, request, context):
        """Creates a new test in the metadata store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestStation(self, request, context):
        """Gets the test station associated with the identifier given in the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTestStations(self, request, context):
        """Perform an OData query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTestStation(self, request, context):
        """Creates a new test station in the metadata store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHardwareItem(self, request, context):
        """Gets the hardware item associated with the identifier given in the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryHardwareItems(self, request, context):
        """Perform an OData query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateHardwareItem(self, request, context):
        """Creates a new hardware item in the metadata store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSoftwareItem(self, request, context):
        """Gets the software item associated with the identifier given in the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySoftwareItems(self, request, context):
        """Perform an OData query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSoftwareItem(self, request, context):
        """Creates a new software item in the metadata store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestAdapter(self, request, context):
        """Gets the test adapter associated with the identifier given in the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTestAdapters(self, request, context):
        """Perform an OData query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTestAdapter(self, request, context):
        """Creates a new test adapter in the metadata store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSchema(self, request, context):
        """Registers a schema. Once a schema has been published, it cannot be modified or removed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchemas(self, request, context):
        """Lists the schemas that have been previously registered
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlias(self, request, context):
        """Gets the alias and its target (i.e., the underlying metadata that it represents)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAliases(self, request, context):
        """Perform an OData query on the registered aliases
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAlias(self, request, context):
        """Creates (registers) an alias of the specified metadata for use/reference when creating other metadata or publishing.
        Notes:
        - The specified metadata must have already been created prior to the alias registration.
        - This method may be called with an already registered alias name in order to update the target mapped for that existing alias.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAlias(self, request, context):
        """Removes a registered alias
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFromJsonDocument(self, request, context):
        """Creates all of the metadata entries contained in the provided JSON document.
        The JSON document should conform to the schema defined by
        https://raw.githubusercontent.com/ni/ni-apis/main/ni/measurements/metadata/v1/registration.schema.json
        The response will contain all of the associated objects from the metadata store.  If the object
        already exists, the existing object will be returned; otherwise, a new object will be created
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUutInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUutInstance,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutInstanceRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutInstanceResponse.SerializeToString,
            ),
            'QueryUutInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryUutInstances,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutInstancesRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutInstancesResponse.SerializeToString,
            ),
            'CreateUutInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUutInstance,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutInstanceRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutInstanceResponse.SerializeToString,
            ),
            'GetUut': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUut,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutResponse.SerializeToString,
            ),
            'QueryUuts': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryUuts,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutsRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutsResponse.SerializeToString,
            ),
            'CreateUut': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUut,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutResponse.SerializeToString,
            ),
            'GetOperator': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperator,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetOperatorRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetOperatorResponse.SerializeToString,
            ),
            'QueryOperators': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOperators,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryOperatorsRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryOperatorsResponse.SerializeToString,
            ),
            'CreateOperator': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOperator,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateOperatorRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateOperatorResponse.SerializeToString,
            ),
            'GetTestDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestDescription,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestDescriptionRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestDescriptionResponse.SerializeToString,
            ),
            'QueryTestDescriptions': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTestDescriptions,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestDescriptionsRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestDescriptionsResponse.SerializeToString,
            ),
            'CreateTestDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTestDescription,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestDescriptionRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestDescriptionResponse.SerializeToString,
            ),
            'GetTest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTest,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestResponse.SerializeToString,
            ),
            'QueryTests': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTests,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestsRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestsResponse.SerializeToString,
            ),
            'CreateTest': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTest,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestResponse.SerializeToString,
            ),
            'GetTestStation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestStation,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestStationRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestStationResponse.SerializeToString,
            ),
            'QueryTestStations': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTestStations,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestStationsRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestStationsResponse.SerializeToString,
            ),
            'CreateTestStation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTestStation,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestStationRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestStationResponse.SerializeToString,
            ),
            'GetHardwareItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHardwareItem,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetHardwareItemRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetHardwareItemResponse.SerializeToString,
            ),
            'QueryHardwareItems': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryHardwareItems,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryHardwareItemsRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryHardwareItemsResponse.SerializeToString,
            ),
            'CreateHardwareItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHardwareItem,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateHardwareItemRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateHardwareItemResponse.SerializeToString,
            ),
            'GetSoftwareItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSoftwareItem,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetSoftwareItemRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetSoftwareItemResponse.SerializeToString,
            ),
            'QuerySoftwareItems': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySoftwareItems,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QuerySoftwareItemsRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QuerySoftwareItemsResponse.SerializeToString,
            ),
            'CreateSoftwareItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSoftwareItem,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateSoftwareItemRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateSoftwareItemResponse.SerializeToString,
            ),
            'GetTestAdapter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestAdapter,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestAdapterRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestAdapterResponse.SerializeToString,
            ),
            'QueryTestAdapters': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTestAdapters,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestAdaptersRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestAdaptersResponse.SerializeToString,
            ),
            'CreateTestAdapter': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTestAdapter,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestAdapterRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestAdapterResponse.SerializeToString,
            ),
            'RegisterSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSchema,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.RegisterSchemaRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.RegisterSchemaResponse.SerializeToString,
            ),
            'ListSchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchemas,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.ListSchemasRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.ListSchemasResponse.SerializeToString,
            ),
            'GetAlias': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlias,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetAliasRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetAliasResponse.SerializeToString,
            ),
            'QueryAliases': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAliases,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryAliasesRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryAliasesResponse.SerializeToString,
            ),
            'CreateAlias': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlias,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateAliasRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateAliasResponse.SerializeToString,
            ),
            'DeleteAlias': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAlias,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.DeleteAliasRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.DeleteAliasResponse.SerializeToString,
            ),
            'CreateFromJsonDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFromJsonDocument,
                    request_deserializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateFromJsonDocumentRequest.FromString,
                    response_serializer=ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateFromJsonDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ni.measurements.metadata.v1.MetadataStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ni.measurements.metadata.v1.MetadataStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetadataStoreService(object):
    """This service is responsible for storing and retrieving metadata associated with test step measurements.
    """

    @staticmethod
    def GetUutInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/GetUutInstance',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutInstanceRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryUutInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/QueryUutInstances',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutInstancesRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUutInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/CreateUutInstance',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutInstanceRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/GetUut',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetUutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryUuts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/QueryUuts',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutsRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryUutsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/CreateUut',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateUutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/GetOperator',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetOperatorRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetOperatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryOperators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/QueryOperators',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryOperatorsRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryOperatorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOperator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/CreateOperator',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateOperatorRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateOperatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/GetTestDescription',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestDescriptionRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestDescriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTestDescriptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/QueryTestDescriptions',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestDescriptionsRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestDescriptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTestDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/CreateTestDescription',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestDescriptionRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestDescriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/GetTest',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/QueryTests',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestsRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/CreateTest',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestStation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/GetTestStation',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestStationRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestStationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTestStations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/QueryTestStations',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestStationsRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestStationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTestStation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/CreateTestStation',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestStationRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestStationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHardwareItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/GetHardwareItem',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetHardwareItemRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetHardwareItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryHardwareItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/QueryHardwareItems',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryHardwareItemsRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryHardwareItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateHardwareItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/CreateHardwareItem',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateHardwareItemRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateHardwareItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSoftwareItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/GetSoftwareItem',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetSoftwareItemRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetSoftwareItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySoftwareItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/QuerySoftwareItems',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QuerySoftwareItemsRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QuerySoftwareItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSoftwareItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/CreateSoftwareItem',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateSoftwareItemRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateSoftwareItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/GetTestAdapter',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestAdapterRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetTestAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTestAdapters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/QueryTestAdapters',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestAdaptersRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryTestAdaptersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTestAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/CreateTestAdapter',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestAdapterRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateTestAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/RegisterSchema',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.RegisterSchemaRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.RegisterSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/ListSchemas',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.ListSchemasRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.ListSchemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/GetAlias',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetAliasRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.GetAliasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAliases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/QueryAliases',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryAliasesRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.QueryAliasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAlias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/CreateAlias',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateAliasRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateAliasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAlias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/DeleteAlias',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.DeleteAliasRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.DeleteAliasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFromJsonDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni.measurements.metadata.v1.MetadataStoreService/CreateFromJsonDocument',
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateFromJsonDocumentRequest.SerializeToString,
            ni_dot_measurements_dot_metadata_dot_v1_dot_metadata__store__service__pb2.CreateFromJsonDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
