name: CI

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  check_protos:
    name: Check .proto files
    uses: ./.github/workflows/check_protos.yml
  check_workflows:
    name: Check workflows
    uses: ./.github/workflows/check_workflows.yml
    permissions:
      security-events: write
  create_ci_artifacts:
    name: Create CI artifacts
    uses: ./.github/workflows/create_ci_artifacts.yml
  trigger_azdo_ci:
    name: Trigger AzDO CI
    uses: ./.github/workflows/trigger_azdo_ci.yml
