name: PR

on:
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  check_protos:
    name: Check .proto files
    uses: ./.github/workflows/check_protos.yml
  check_workflows:
    name: Check workflows
    uses: ./.github/workflows/check_workflows.yml
    permissions:
      security-events: write
