name: Trigger AzDO CIs

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger_azdo_ci:
    name: Trigger Main CI
    runs-on: windows-latest
    steps:
    - name: Trigger Main CI 
      uses: Azure/pipelines@fac73367a779c3bd02c073d6c41bc81d18b2c0ad # v1.2
      if: ${{ github.repository == 'ni/ni-apis' }}
      with:
        azure-devops-project-url: 'https://dev.azure.com/ni/DevCentral'
        azure-pipeline-name: 'ASW-ni-apis-ci'
        azure-devops-token: ${{ secrets.AZDO_PIPELINE_TRIGGERS }}
        azure-pipeline-variables: '{"BRANCH": "main", "EXPORT_NAME": "ni-apis", "PHASE": "d"}'
